apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc }}
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | b64enc }}
  DATABASE_USER: {{ .Values.secrets.databaseUser | b64enc }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc }}


