apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  PORT: "3000"                          # all values are strings
  NODE_ENV: "production"
  DATABASE_HOST: "postgres-svc"
  DATABASE_NAME: "bettracker"
  DATABASE_PORT: "5432"
  REDIS_URL: "redis://redis-svc:6379"
  POSTGRES_DB: "bettracker"